### ISSUE TITLE
想问下这个是游戏驱动还是工作室驱动？

### ISSUE THREAD

**Issue by 1090184523** [WhatTheBlock/GeForce-Driver-Lite#2]
想问下这个是游戏驱动还是工作室驱动？

**Comment by WhatTheBlock** [comment]
目前都是遊戲驅動哦
有需要更新Studio驅動嗎?

**Comment by WhatTheBlock** [comment]
### [DCH-Studio-531.41](https://github.com/WhatTheBlock/GeForce-Driver-Lite/releases/tag/dch-studio-531.41)

Studio驅動已更新
