### ISSUE TITLE
GTX 950M 快速安裝失敗

### ISSUE THREAD

**Issue by IM71** [WhatTheBlock/GeForce-Driver-Lite#3]
您好

顯示卡為 GTX 950M
想要直接更新至 DCH-551.46 但顯示失敗 (目前是在 DCH-536.40)
想請問該如何解決錯誤?

謝謝

**Comment by WhatTheBlock** [comment]
我是沒遇到問題，試試全新安裝吧

**Comment by IM71** [comment]
> 我是沒遇到問題，試試全新安裝吧

已重新安裝，成功更新到新版
謝謝
